### ISSUE TITLE
updated spacewalk recipe

### ISSUE THREAD

**Issue by ghost** [philicious/spacewalk-server-chef#4]
Phil,

Wasn't sure how to actually get this to you other than making a pull request. I have had to make get spacewalk in our environment and noticed that you had a chef recipe. Your basically got me started with the install but I realized there was much more that could be done. I'd like to share with you what I have done and maybe if you like you can include it in yours or just leave it be.

There is much that I changed since our environment is purely a RHEL shop, so I removed all the debian/ubuntu stuff. But I think the core coding I did you will like.

**Comment by philicious** [comment]
Hey !
Sounds good. Just open a PR and I will have a look at your code and we might get it merged in.

**Comment by ghost** [comment]
:( Very sorry but just got informed I cannot share the work I did as it violates company policy. Its kinda lame but again I completely apologies for the trouble.

**Comment by philicious** [comment]
to bad but dont worry :/ I know the feeling fighting / giving up against company policies...

maybe you can convience your boss with the fact that this cookbook (and the one for the client) was done and shared by another company. You could even add that info to the license, see https://github.com/philicious/spacewalk-server-chef/blob/master/LICENSE#L2-L3
