### ISSUE TITLE
centos issue

### ISSUE THREAD

**Issue by chlsmith** [philicious/spacewalk-server-chef#5]
I don't think this is specific to CentOS 7, but I'm trying to get spacewalk to install.   First, it's missing a couple of perl dependencies, but then the "--disconnected" option is not working when spacewalk-setup is being executed.  

for more info on the dependencies, check out http://jensd.be/232/linux/spacewalk-installation-on-centos-7.   I don't know why the disconnected part is failing, but it certainly is on my VM.

**Comment by philicious** [comment]
@chlsmith I havent used this cookbook with Spacewalk 2.3/2.4 myself. So there indeed might be certain things that need to be addressed / adjusted.
However I will very likely setup a new Spacewalk instance in the next few weeks and also update this cookbook then. 
Any feedback or bugfixes etc are welcome :)

About the `--disconnected` problem, would you have some more details like an output log ?

**Comment by philicious** [comment]
closing this as I just installed SW 2.6 on CentOS7 without any problems, following https://github.com/spacewalkproject/spacewalk/wiki/HowToInstall
This cookbook should still work. Gonna test it later
